// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!


// based on PICO_CONFIG_HEADER_FILES:

#include "/home/andy/proj/thirdparty/pico-sdk/src/boards/include/boards/pico.h"

// based on PICO_RP2040_CONFIG_HEADER_FILES:

#include "/home/andy/proj/thirdparty/pico-sdk/src/rp2_common/cmsis/include/cmsis/rename_exceptions.h"

// aks: Adding a few things I couldn't find elsewhere.
#define PRIu64 "lld"
